language: java
jdk:
- openjdk8

branches:
  only:
  - master
  - development

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - gradle -PossrhUsername=${ossrhUsername} -PossrhPassword=${ossrhPassword} install dockerBuildImage

script:
  # extract the ivct version tag
  - export VERSION=$(grep "ivctVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
  # tag branch version
  - docker tag ivct/logsink:$VERSION ivct/logsink:$TRAVIS_BRANCH-latest
  - docker tag ivct/runtime-config:$VERSION ivct/runtime-config:$TRAVIS_BRANCH-latest
  - docker tag ivct/gui:$VERSION ivct/gui:$TRAVIS_BRANCH-latest
  - docker tag ivct/tc-runner:pi-skeleton-$VERSION ivct/tc-runner:pi-skeleton-$TRAVIS_BRANCH-latest
  - docker tag ivct/tc-runner:po-$VERSION ivct/tc-runner:po-$TRAVIS_BRANCH-latest
  - docker tag ivct/tc-runner:ma-$VERSION ivct/tc-runner:ma-$TRAVIS_BRANCH-latest
  # push images to docker hub
  - docker push ivct/logsink
  - docker push ivct/tc-runner
  - docker push ivct/gui
  - docker push ivct/runtime-config

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
