language: java
jdk: 
  - oraclejdk8
sudo: true

install: true

env:
  - CI=true

jobs:
  include:
    - stage: build distributions
      script: gradle install
    - stage: build LogSink Docker image
      before_script: cd LogSink
      script: docker build --build-arg version=1.0.1 -t msg134/logsink:latest .
      
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/