language: java
sudo: true
jdk: oraclejdk8

install: true

jobs:
  include:
    - stage: build distributions
      script: gradle install
    - stage: build LogSink Docker image
      before_script: cd LogSink
      script: docker build --build-arg version=1.0.1 -t msg134/logsink:latest .