== Terminology

The IVCTool is using many different concepts, which are briefly explained below:

* _Conformance Statement (CS)_: A SuT defines its behavior with a Conformance Statement. This includes the name, version and description of the SuT, and a list of Interoperability Badges fulfilled by the SuT. These badges are considered as the capabilities of the SuT.

* _Interoperability Badge_: The Interoperability Badge is a named list of interoperability requirements. It therefor represents a defined and referable interoperability pattern.

* _Interoperability Requirement_: A interoperability requirement is a named requirement, representing a basic behavior definition a federate has to fulfill in order to be considered interoperable.

* _IVCT Operator_: The IVCT Operator is the person using the IVCTool to setup the SuT configuration and to execute the test cases, in order to verify the SuT's Conformance Statement.

* _Test Case_: A test case is the algorithm to verify a interoperability requirement. In most cases the term _test case_ referes to an _executable test case_, which is Java class with an execute method to be run within the _test case engine_. There is also the concept of an _abstract test case_, which refers to a specification of the test case algorithm. An abstract test case can be used as complementary information for an interoperability requirement. In the context of the IVCTool only executable test cases are used.

* _Test Engine_: The test engine is the IVCTool component that executes a test case. The engine needs to be compiled and configured for a certain HLA run-time infrastructure. Changing the run-time infrastructure (RTI) is currently not possible by replacing the test engine.

* _Test Suite_: A test suite is a container for test cases which are sharing the same configuration parameters. It used mainly a convenience feature to bundle test code into one build repository and to simplify the test case configuration.

* _System under Test (SuT)_: The system under test is a simulation system that is being tested. It is defined by an identifier, a version, a human readable name, a vendor marking, a conformance statement, a description to explain the system purpose, and connection information to the representing federate.

* _System under Test Environment (SuTE)_: In many cases, a SuT requires federated partners to interact with or to provide trigger events to perform a certain behavior. Such partners are not subject of the test, but may be required as the System under Test Environment.


to be completed...
