= IVCT Documentation

This page gives an overview of the available documentation for the IVCT Framework code.
It is designed for system integrators, framework and test case developers.

NOTE: The documentation pages are currently under construction.
Some pages might be outdated or unfinished.


== Preparations

A good starting point to get a bit of an background on the architecture are the
following sections.

* <<1-1-IVCT-Module-Overview.adoc#,IVCT Module Overview>>
* <<1-2-model.adoc#,IVCT Information Model (draft for discussion)>>
* <<1-3-badge2testsuite.adoc#,Linking Interoperability Badges with Test Suites>>

== Building the software
If you plan do build the software by yourself, the following sections will give
you an overview on tools and the development environment.

* <<2-1-build-overview.adoc#,The IVCTool Software Build Environment>>
* <<2-2-prerequisites.adoc#,Prerequisites for participating in IVCT_Framework development>>
* <<2-3-Branching-and-Merging.adoc#,Guidelines for branching and merging>>
* <<2-4-gradleDoc.adoc#,Building the IVCT_Framework with gradle>>
* <<2-5-travis.adoc#,Automatic testing, building, docker image building and deployment using Travis-CI>>
* <<2-6-3rdpartyRti.adoc#,Using the framework with a 3rd-party RTI Implementation>>
* <<2-7-TClogging.adoc#,Test case logging>>
* <<2-8-IVCT_Configuration.adoc#,Configuration of the IVCTool>>

== Docker Images
The primary deployment typ for the IVCTool is the containerization with docker images.
The underlying concept and configurations are explained below.

* <<3-1-IVCT-Container-Design.adoc#,IVCT Container design>>
* <<3-2-IVCT-TC-Runner-Application-image.adoc#,IVCT TC Runner Application-image>>
* <<3-3-IVCT-GUI-image.adoc#,IVCT GUI image>>
* <<3-4-IVCT-LogSink-Application-image.adoc#,IVCT LogSink Application image>>
* <<3-5-Building-Docker-images.adoc#,Building Docker images for IVCT Framework Components>>


== Running the tools
To use the IVCTool there are two types of interfaces available, a web-based and a
commandline-based UI. These are described below, as well as some background on
reading log files and the available test suite.

* <<4-1-Setup-the-JMS-broker.adoc#,Setup the JMS broker>>
* <<4-2-Graphical-User-Interface.adoc#,The graphical user interface>>
* <<4-3-commandlinetool#,The command line interface>>
* <<4-4-Reading-and-understanding-Test-Case-logfiles.adoc#,Reading and understanding Test Case logfiles>>
* <<4-5-testsuite-overview.adoc#,Testsuite Overview>>
* <<4-6-Local-Settings-Designator.adoc#,Local SettingsDesignator>>

== Extending the framework
Finally there are some guidelines on writing test cases and considerations for
guture enhancements.

* <<5-1-TcDevelGuide.adoc#,Test Case Development Guide>>
* <<5-2-Executable-Test-Case-Development-Rules.adoc#,Executable Test Case Development Rules>>
* <<5-3-Add-new-test-suites.adoc#,Add new test suites>>
* <<5-4-futureenhancements.adoc#,Future enhancements>>
