= IVCT TC-Runner Application image

The Testcase Runner component image extends a Local RTI Component (LRC) image hosted in the **app-docker136.hex.tno.nl** Docker registry. The LRC image is a minimal image and provides basic functionality to launch an HLA federate application. Several LRC images are available for different RTI implementations (Pitch, Mak, Portico) and Linux distributions (Alpine, Debian, CentOS). Each LRC image includes a Java JRE. An LRC image sets the LRC libraries in the $CLASSPATH and $LD_LIBRARYPATH and provides several environment variables to control the behavior of the LRC. For more information see the LRC image documentation.

== Environment Variables

| Environment Variable Name  | Description | Default if not set |
| ------------- | ------------- | ------------- |
| ACTIVEMQ_HOST | Hostname/IP of the Active MQ host | `localhost` |
| ACTIVEMQ_PORT | Port at which Active MQ can be reached at the host | `61616` |
| IVCT_CONF | References either a directory with the properties file named `IVCT.properties` or to the properties file itself. See also [IVCT Configuration directory](https://github.com/MSG134/IVCT_Framework/wiki/IVCT_Configuration). | Default properties (will be /root/conf) |

For more environment variables see the LRC image documentation.
