import static org.junit.Assert.assertTrue;

import java.io.IOException;

import org.junit.Test;

import nato.ivct.commander.CmdListSuT;
import nato.ivct.commander.CmdStartTestResultListener.OnResultListener;
import nato.ivct.commander.CmdStartTestResultListener.TcResult;
import nato.ivct.commander.Factory;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hzg' at '07.04.17 10:59' with Gradle 2.9
 *
 * @author hzg, @date 07.04.17 10:59
 */
public class FactoryTest {
	@Test
	public void testCreateCmdListBadgesMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("Factory Test createCmdListBadges should return CmdListBadges", classUnderTest.createCmdListBadges() != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCreateCmdListSutMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("Factory Test createCmdListSut should return CmdListSut", classUnderTest.createCmdListSut() != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCreateCmdQuitMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("Factory Test createCmdQuit should return CmdQuit", classUnderTest.createCmdQuit() != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCreateCmdSetLogLevelMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("Factory Test createCmdSetLogLevel should return CmdSetLogLevel", classUnderTest.createCmdSetLogLevel("debug") != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCreateCmdStartTcMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("Factory Test createCmdStartTc should return CmdStartTc", classUnderTest.createCmdStartTc("hw_iosb", "TS_HelloWorld", "some.test.case", "c:/tmp") != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testCreateCmdStartTestResultListenerMethod() {
		Factory classUnderTest;
		class OnResultListenerTest implements OnResultListener {

			@Override
			public void OnResult(TcResult result) {
				// TODO Auto-generated method stub
				
			}
			
		}
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			OnResultListener testListener = new OnResultListenerTest();
			assertTrue("Factory Test createCmdStartTestResultListener should return CmdStartTestResultListener", classUnderTest.createCmdStartTestResultListener(testListener) != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	@Test
	public void testHelloWorldFederate () {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			CmdListSuT cmd = classUnderTest.createCmdListSut();
			cmd.execute();
			assertTrue("should have a list of SuTs", cmd.sutMap != null);
			assertTrue("hw_iosb should exist", cmd.sutMap.containsKey("hw_iosb"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
