import static org.junit.Assert.assertTrue;

import java.io.IOException;

import org.junit.Test;

import nato.ivct.commander.Factory;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hzg' at '07.04.17 10:59' with Gradle 2.9
 *
 * @author hzg, @date 07.04.17 10:59
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Factory classUnderTest;
		try {
			classUnderTest = new Factory();
			classUnderTest.initialize();
			assertTrue("someLibraryMethod should return 'true'", classUnderTest.createCmdListSut() != null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
