FROM hlacontainers/lrc:vtmak-4.5f-centos7

ARG version

ADD ./build/distributions/TC.exec-${version}.tar /root/application/

ADD ./docker/start.sh /root/application/start.sh

RUN ln -s /root/application/TC.exec-${version} /root/application/TC.exec

RUN chmod a+x /root/application/start.sh

ENV LRC_ENTRYPOINT=/root/application/start.sh
