# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: 
      - development
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle -PossrhUsername=${ossrhUsername} -PossrhPassword=${ossrhPassword} install dockerBuildImage
    
    - name: Read IVCT Version tag
      run: export VERSION=$(grep "helloWorldVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
    
    - name: Tag docker images
      run: |
        docker tag ivct/logsink:$VERSION ivct/logsink:$GITHUB_REF-latest
        docker tag ivct/runtime-config:$VERSION ivct/runtime-config:$GITHUB_REF-latest
        docker tag ivct/gui:$VERSION ivct/gui:$GITHUB_REF-latest
        docker tag ivct/tc-runner:pi-skeleton-$VERSION ivct/tc-runner:pi-skeleton-$GITHUB_REF-latest
        docker tag ivct/tc-runner:po-$VERSION ivct/tc-runner:po-$GITHUB_REF-latest
        docker tag ivct/tc-runner:ma-$VERSION ivct/tc-runner:ma-$GITHUB_REF-latest
    
    - name: Log into DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
    - name: Push images to DockerHub
      run: |
        docker push ivct/logsink
        docker push ivct/tc-runner
        docker push ivct/gui
        docker push ivct/runtime-config

