# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish Docker Images

on:
  push:
    branches: 
      - development
      - master

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      VERSION: 'undefined'
      PossrhUsername: ${{ secrets.PossrhUsername }}
      PossrhPassword: ${{ secrets.PossrhPassword }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Read IVCT Version tag
      run: |
        VERSION=$(grep "ivctVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
        echo "Building version ${VERSION}"
        echo "Building version ${env.VERSION}"
        env.VERSION= {{ grep "ivctVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \' }}
        echo "Building version ${env.VERSION}"
    
    - name: Build with Gradle
      run: ./gradlew -PossrhUsername=${ossrhUsername} -PossrhPassword=${ossrhPassword} install dockerBuildImage
    
    - name: Tag docker images
      run: |
        echo "Building version ${env.VERSION} for branch ${GITHUB_REF:11}"
        docker tag ivct/logsink:${env.VERSION} ivct/logsink:${GITHUB_REF:11}-latest
        docker tag ivct/runtime-config:${env.VERSION} ivct/runtime-config:${GITHUB_REF:11}-latest
        docker tag ivct/gui:${env.VERSION} ivct/gui:${GITHUB_REF:11}-latest
        docker tag ivct/tc-runner:pi-skeleton-${env.VERSION} ivct/tc-runner:pi-skeleton-${GITHUB_REF:11}-latest
        docker tag ivct/tc-runner:po-${env.VERSION} ivct/tc-runner:po-${GITHUB_REF:11}-latest
        docker tag ivct/tc-runner:ma-${env.VERSION} ivct/tc-runner:ma-${GITHUB_REF:11}-latest
    
    - name: Log into DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
    - name: Push images to DockerHub
      run: |
        docker image ls
        docker push ivct/logsink:${VERSION}
        docker push ivct/runtime-config:${VERSION}
        docker push ivct/gui:${VERSION}
        docker push ivct/tc-runner:pi-skeleton-${VERSION}
        docker push ivct/tc-runner:po-${VERSION}
        docker push ivct/tc-runner:ma-${VERSION}

